# Generated by Django 2.1.3 on 2018-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0002_auto_20181208_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
