# Generated by Django 2.1.3 on 2018-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0003_auto_20181208_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
