# Generated by Django 2.1.3 on 2018-12-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0004_auto_20181208_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='phone',
            field=models.CharField(max_length=42),
        ),
    ]
