# Generated by Django 2.1.3 on 2019-03-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0005_auto_20181208_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_a',
            fields=[
                ('name_client_z', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('client_type_z', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='user_a',
            fields=[
                ('first_name', models.CharField(max_length=42)),
                ('middle_name', models.CharField(blank=True, max_length=42)),
                ('last_name', models.CharField(max_length=42)),
                ('job_title', models.CharField(blank=True, max_length=42)),
                ('email', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('office_phone', models.IntegerField(blank=True)),
                ('cell_phone', models.IntegerField(blank=True)),
                ('password', models.CharField(blank=True, max_length=42)),
                ('prefix', models.CharField(blank=True, max_length=42)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.client_a')),
            ],
        ),
    ]
