# Generated by Django 2.1.3 on 2019-03-02 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0006_client_a_user_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('client_name', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('client_type', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address1', models.CharField(blank=True, max_length=42)),
                ('address2', models.CharField(blank=True, max_length=42)),
                ('city', models.CharField(blank=True, max_length=42)),
                ('state', models.CharField(blank=True, max_length=42)),
                ('zip', models.CharField(blank=True, max_length=42)),
                ('country', models.CharField(blank=True, max_length=42)),
                ('phone', models.IntegerField(blank=True)),
                ('fax', models.IntegerField(blank=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.client')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('first_name', models.CharField(max_length=42)),
                ('middle_name', models.CharField(blank=True, max_length=42)),
                ('last_name', models.CharField(max_length=42)),
                ('job_title', models.CharField(blank=True, max_length=42)),
                ('email', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('office_phone', models.IntegerField(blank=True)),
                ('cell_phone', models.IntegerField(blank=True)),
                ('password', models.CharField(blank=True, max_length=42)),
                ('prefix', models.CharField(blank=True, max_length=42)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.client')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_a',
            name='client_id',
        ),
        migrations.DeleteModel(
            name='client_a',
        ),
        migrations.DeleteModel(
            name='user_a',
        ),
    ]
