# Generated by Django 2.1.3 on 2019-03-02 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0007_auto_20190302_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('service_name', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('service_description', models.CharField(blank=True, max_length=42)),
                ('fi_required', models.CharField(blank=True, max_length=42)),
                ('fi_frequency', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='test_standard',
            fields=[
                ('test_name', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('test_description', models.CharField(blank=True, max_length=42)),
                ('publish_date', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='test_standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.test_standard'),
        ),
    ]
