# Generated by Django 2.1.3 on 2019-03-02 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='performance',
            fields=[
                ('performance_id', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('max_system_voltage', models.CharField(blank=True, max_length=42)),
                ('name', models.CharField(blank=True, max_length=42)),
                ('open_circuit_voltage', models.CharField(blank=True, max_length=42)),
                ('short_circuit_current', models.CharField(blank=True, max_length=42)),
                ('voltage_at_max_power', models.CharField(blank=True, max_length=42)),
                ('current_at_max_power', models.CharField(blank=True, max_length=42)),
                ('max_power_output', models.CharField(blank=True, max_length=42)),
                ('fill_factor', models.CharField(blank=True, max_length=42)),
                ('model_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.product')),
            ],
        ),
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('sequence_id', models.CharField(max_length=42, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='sequenc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.sequence'),
        ),
    ]
