# Generated by Django 2.1.3 on 2019-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0011_auto_20190302_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='sequence_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
