# Generated by Django 2.1.3 on 2019-03-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0012_sequence_sequence_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=42)),
                ('y', models.CharField(max_length=42)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tempp',
            unique_together={('x', 'y')},
        ),
    ]
