# Generated by Django 2.1.3 on 2019-03-08 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0014_temp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempp',
            name='z',
            field=models.CharField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tempp',
            unique_together={('x', 'y', 'z')},
        ),
    ]
