# Generated by Django 2.1.3 on 2019-03-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0015_auto_20190308_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempp',
            name='m',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterUniqueTogether(
            name='tempp',
            unique_together={('x', 'y', 'z', 'm')},
        ),
    ]
