# Generated by Django 2.1.3 on 2019-03-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0018_auto_20190308_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate_no_generator',
            name='color',
        ),
        migrations.AddField(
            model_name='certificate_no_generator',
            name='pv_type_code',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=6),
        ),
    ]
