# Generated by Django 2.1.3 on 2019-03-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0019_auto_20190308_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_no_generator',
            name='pv_type_code',
            field=models.CharField(choices=[('one', 'ONE'), ('two', 'TWO'), ('Three', 'THREE'), ('four', 'FOUR'), ('five', 'FIVE')], default=1, max_length=6),
        ),
    ]
