# Generated by Django 2.1.3 on 2019-03-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0020_auto_20190308_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate_no_generator',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='certificate_no_generator',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='certificate_no_generator',
            name='s3',
        ),
        migrations.AddField(
            model_name='certificate_no_generator',
            name='seq',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='certificate_no_generator',
            name='pv_type_code',
            field=models.CharField(choices=[(1, 'ONE'), (2, 'TWO'), (3, 'THREE'), (4, 'FOUR'), (5, 'FIVE')], default=1, max_length=6),
        ),
    ]
