# Generated by Django 2.1.3 on 2019-03-08 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0022_auto_20190308_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_no_generator',
            name='cert_type_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='certificate_no_generator',
            name='pv_type_code',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='certificate_no_generator',
            unique_together={('cert_type_code', 'subsidiary_code', 'year_code', 'pv_type_code', 'seq')},
        ),
    ]
