# Generated by Django 2.1.3 on 2019-03-08 23:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0023_auto_20190308_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificategenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1000)),
                ('cert_type_code', models.CharField(blank=True, max_length=2)),
                ('subsidiary_code', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('year_code', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)])),
                ('pv_type_code', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='certificatex',
            fields=[
                ('cer_id', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=42)),
                ('issue_date', models.CharField(blank=True, max_length=42)),
                ('cert_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.certificategenerator')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.client')),
                ('locc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.location')),
                ('produc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.product')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.factory_inspection')),
                ('test_std', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.test_standard')),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='locc_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='produc',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='report',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='test_std',
        ),
        migrations.DeleteModel(
            name='certificate_no_generator',
        ),
        migrations.DeleteModel(
            name='certificate',
        ),
        migrations.AlterUniqueTogether(
            name='certificategenerator',
            unique_together={('cert_type_code', 'subsidiary_code', 'year_code', 'pv_type_code', 'seq')},
        ),
    ]
