# Generated by Django 2.1.3 on 2019-03-08 23:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eren', '0025_auto_20190308_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificatey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=42)),
                ('issue_date', models.CharField(blank=True, max_length=42)),
                ('cert_page_number', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(10)])),
                ('cert_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.certificategenerator')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.client')),
                ('locc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.location')),
                ('produc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.product')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.factory_inspection')),
                ('test_std', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eren.test_standard')),
            ],
        ),
        migrations.RemoveField(
            model_name='certificatex',
            name='cert_no',
        ),
        migrations.RemoveField(
            model_name='certificatex',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='certificatex',
            name='locc_id',
        ),
        migrations.RemoveField(
            model_name='certificatex',
            name='produc',
        ),
        migrations.RemoveField(
            model_name='certificatex',
            name='report',
        ),
        migrations.RemoveField(
            model_name='certificatex',
            name='test_std',
        ),
        migrations.DeleteModel(
            name='certificatex',
        ),
    ]
